# Generated by Django 4.2.7 on 2023-11-27 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_category_options_post_case'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='case',
            new_name='category',
        ),
    ]
